# 应用服务 WEB 访问端口
server:
  port: 8891
spring:
  # redis配置
  data:
    redis:
#      host: 192.168.1.11
      host: 127.0.0.1
      port: 6379
      timeout: 5s
      database: 2
      # redis1121
      password: 20241201
#      password:
    # 连接超时时间

# 为不同业务设置不同的数据库
redis:
  database:
    platform: 3

# 扫水服务器数
sweepwater:
  server:
    count: 1